
development:
  adapter: postgresql
  encoding: unicode
  database: example_csv_import_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: example_csv_import_test
  pool: 5
  host: localhost
